apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    maintainer: klaus
  name: dbactions4si-cdb
  namespace: sidb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dbactions4si-cdb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dbactions4si-cdb
    spec:
      containers:
      - env:
        - name: ORACLE_SERVICE
          value: orcl1
        - name: ORACLE_HOST
          value: si-cdb.sidb.svc.cluster.local
        - name: ORACLE_PORT
          value: '1521'
        - name: ORACLE_PWD
          value: ORacle_21c
        - name: ORDS_PWD
          value: ORacle_21c
        image: phx.ocir.io/intsanjaysingh/db-operator/sharding:restdataservices-21.2.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: 8888
          timeoutSeconds: 1
        name: dbactions4si-cdb
        ports:
        - containerPort: 8888
          name: containerport
        resources:
          limits:
            cpu: "1"
            memory: 2000Mi
          requests:
            cpu: 500m
            memory: 1000Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /opt/oracle/ords/config/ords
          name: tmp-config
        - mountPath: /opt/oracle/ords/params
          name: tmp-params
        - mountPath: /tmp
          name: tmp-tmp
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      securityContext:
        fsGroup: 54322
        runAsUser: 54321
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp-config
      - emptyDir: {}
        name: tmp-params
      - emptyDir: {}
        name: tmp-tmp
---
apiVersion: v1
kind: Service
metadata:
  name: lbsv4dbactions4si-cdb
  namespace: sidb
spec:
  loadBalancerIP: 152.70.179.193
  ports:
  - name: http-ords
    port: 8888
    targetPort: 8888
    protocol: TCP
  selector:
    app: dbactions4si-cdb
  type: LoadBalancer

