apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-sharding-db-connection-manager
  namespace: shns
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: oracle-sharding-db-connection-manager
  template:
    metadata:
      labels:
        app: oracle-sharding-db-connection-manager
    spec:
      containers:
      - env:
        - name: PORT
          value: "1521"
        - name: PUBLIC_HOSTNAME
          value: localhost
        - name: PUBLIC_IP
          value: 127.0.0.1
        image: phx.ocir.io/intsanjaysingh/db-operator/sharding:cman-21.3.0
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 30
          tcpSocket:
            port: 1521
        name: oracle-sharding-db-connection-manager
        resources:
          requests:
            memory: "2000Mi"
            cpu: "3000m"
        ports:
        - containerPort: 1521
          protocol: TCP
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-db-connection-manager-service-permanent-ip
  namespace: shns
spec:
  loadBalancerIP: 132.145.255.210
  ports:
    - port: 1521
      targetPort: 1521
      protocol: TCP
  selector:
    app: oracle-sharding-db-connection-manager
  type: LoadBalancer
